TEMPLATE = app

QT += qml quick
CONFIG += c++11

SOURCES += main.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Default rules for deployment.
include(deployment.pri)

DISTFILES += \
    modules/Material/Extras/js/dateutils.js \
    modules/Material/Extras/js/httplib.js \
    modules/Material/Extras/js/listutils.js \
    modules/Material/Extras/js/promises.js \
    modules/Material/Extras/js/utils.js \
    modules/Material/awesome.js \
    modules/Material/fonts/fontawesome/FontAwesome.otf \
    modules/Material/fonts/roboto/Roboto-Black.ttf \
    modules/Material/fonts/roboto/Roboto-BlackItalic.ttf \
    modules/Material/fonts/roboto/Roboto-Bold.ttf \
    modules/Material/fonts/roboto/Roboto-BoldItalic.ttf \
    modules/Material/fonts/roboto/Roboto-Italic.ttf \
    modules/Material/fonts/roboto/Roboto-Light.ttf \
    modules/Material/fonts/roboto/Roboto-LightItalic.ttf \
    modules/Material/fonts/roboto/Roboto-Medium.ttf \
    modules/Material/fonts/roboto/Roboto-MediumItalic.ttf \
    modules/Material/fonts/roboto/Roboto-Regular.ttf \
    modules/Material/fonts/roboto/Roboto-Thin.ttf \
    modules/Material/fonts/roboto/Roboto-ThinItalic.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-Bold.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-BoldItalic.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-Italic.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-Light.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-LightItalic.ttf \
    modules/Material/fonts/roboto/RobotoCondensed-Regular.ttf \
    modules/Material/icons/main.sh \
    modules/Material/Extras/images/circle.png \
    modules/Material/icons/action/3d_rotation.svg \
    modules/Material/icons/action/accessibility.svg \
    modules/Material/icons/action/accessible.svg \
    modules/Material/icons/action/account_balance.svg \
    modules/Material/icons/action/account_balance_wallet.svg \
    modules/Material/icons/action/account_box.svg \
    modules/Material/icons/action/account_circle.svg \
    modules/Material/icons/action/add_shopping_cart.svg \
    modules/Material/icons/action/alarm.svg \
    modules/Material/icons/action/alarm_add.svg \
    modules/Material/icons/action/alarm_off.svg \
    modules/Material/icons/action/alarm_on.svg \
    modules/Material/icons/action/all_out.svg \
    modules/Material/icons/action/android.svg \
    modules/Material/icons/action/announcement.svg \
    modules/Material/icons/action/aspect_ratio.svg \
    modules/Material/icons/action/assessment.svg \
    modules/Material/icons/action/assignment.svg \
    modules/Material/icons/action/assignment_ind.svg \
    modules/Material/icons/action/assignment_late.svg \
    modules/Material/icons/action/assignment_return.svg \
    modules/Material/icons/action/assignment_returned.svg \
    modules/Material/icons/action/assignment_turned_in.svg \
    modules/Material/icons/action/autorenew.svg \
    modules/Material/icons/action/backup.svg \
    modules/Material/icons/action/book.svg \
    modules/Material/icons/action/bookmark.svg \
    modules/Material/icons/action/bookmark_border.svg \
    modules/Material/icons/action/bug_report.svg \
    modules/Material/icons/action/build.svg \
    modules/Material/icons/action/cached.svg \
    modules/Material/icons/action/camera_enhance.svg \
    modules/Material/icons/action/card_giftcard.svg \
    modules/Material/icons/action/card_membership.svg \
    modules/Material/icons/action/card_travel.svg \
    modules/Material/icons/action/change_history.svg \
    modules/Material/icons/action/check_circle.svg \
    modules/Material/icons/action/chrome_reader_mode.svg \
    modules/Material/icons/action/class.svg \
    modules/Material/icons/action/code.svg \
    modules/Material/icons/action/compare_arrows.svg \
    modules/Material/icons/action/copyright.svg \
    modules/Material/icons/action/credit_card.svg \
    modules/Material/icons/action/dashboard.svg \
    modules/Material/icons/action/date_range.svg \
    modules/Material/icons/action/delete.svg \
    modules/Material/icons/action/description.svg \
    modules/Material/icons/action/dns.svg \
    modules/Material/icons/action/done.svg \
    modules/Material/icons/action/done_all.svg \
    modules/Material/icons/action/donut_large.svg \
    modules/Material/icons/action/donut_small.svg \
    modules/Material/icons/action/eject.svg \
    modules/Material/icons/action/event.svg \
    modules/Material/icons/action/event_seat.svg \
    modules/Material/icons/action/exit_to_app.svg \
    modules/Material/icons/action/explore.svg \
    modules/Material/icons/action/extension.svg \
    modules/Material/icons/action/face.svg \
    modules/Material/icons/action/favorite.svg \
    modules/Material/icons/action/favorite_border.svg \
    modules/Material/icons/action/feedback.svg \
    modules/Material/icons/action/find_in_page.svg \
    modules/Material/icons/action/find_replace.svg \
    modules/Material/icons/action/fingerprint.svg \
    modules/Material/icons/action/flight_land.svg \
    modules/Material/icons/action/flight_takeoff.svg \
    modules/Material/icons/action/flip_to_back.svg \
    modules/Material/icons/action/flip_to_front.svg \
    modules/Material/icons/action/gavel.svg \
    modules/Material/icons/action/get_app.svg \
    modules/Material/icons/action/gif.svg \
    modules/Material/icons/action/grade.svg \
    modules/Material/icons/action/group_work.svg \
    modules/Material/icons/action/help.svg \
    modules/Material/icons/action/help_outline.svg \
    modules/Material/icons/action/highlight_off.svg \
    modules/Material/icons/action/history.svg \
    modules/Material/icons/action/home.svg \
    modules/Material/icons/action/hourglass_empty.svg \
    modules/Material/icons/action/hourglass_full.svg \
    modules/Material/icons/action/http.svg \
    modules/Material/icons/action/https.svg \
    modules/Material/icons/action/important_devices.svg \
    modules/Material/icons/action/info.svg \
    modules/Material/icons/action/info_outline.svg \
    modules/Material/icons/action/input.svg \
    modules/Material/icons/action/invert_colors.svg \
    modules/Material/icons/action/label.svg \
    modules/Material/icons/action/label_outline.svg \
    modules/Material/icons/action/language.svg \
    modules/Material/icons/action/launch.svg \
    modules/Material/icons/action/lightbulb_outline.svg \
    modules/Material/icons/action/line_style.svg \
    modules/Material/icons/action/line_weight.svg \
    modules/Material/icons/action/list.svg \
    modules/Material/icons/action/lock.svg \
    modules/Material/icons/action/lock_open.svg \
    modules/Material/icons/action/lock_outline.svg \
    modules/Material/icons/action/loyalty.svg \
    modules/Material/icons/action/markunread_mailbox.svg \
    modules/Material/icons/action/motorcycle.svg \
    modules/Material/icons/action/note_add.svg \
    modules/Material/icons/action/offline_pin.svg \
    modules/Material/icons/action/opacity.svg \
    modules/Material/icons/action/open_in_browser.svg \
    modules/Material/icons/action/open_in_new.svg \
    modules/Material/icons/action/open_with.svg \
    modules/Material/icons/action/pageview.svg \
    modules/Material/icons/action/pan_tool.svg \
    modules/Material/icons/action/payment.svg \
    modules/Material/icons/action/perm_camera_mic.svg \
    modules/Material/icons/action/perm_contact_calendar.svg \
    modules/Material/icons/action/perm_data_setting.svg \
    modules/Material/icons/action/perm_device_information.svg \
    modules/Material/icons/action/perm_identity.svg \
    modules/Material/icons/action/perm_media.svg \
    modules/Material/icons/action/perm_phone_msg.svg \
    modules/Material/icons/action/perm_scan_wifi.svg \
    modules/Material/icons/action/pets.svg \
    modules/Material/icons/action/picture_in_picture.svg \
    modules/Material/icons/action/picture_in_picture_alt.svg \
    modules/Material/icons/action/play_for_work.svg \
    modules/Material/icons/action/polymer.svg \
    modules/Material/icons/action/power_settings_new.svg \
    modules/Material/icons/action/pregnant_woman.svg \
    modules/Material/icons/action/print.svg \
    modules/Material/icons/action/query_builder.svg \
    modules/Material/icons/action/question_answer.svg \
    modules/Material/icons/action/receipt.svg \
    modules/Material/icons/action/record_voice_over.svg \
    modules/Material/icons/action/redeem.svg \
    modules/Material/icons/action/reorder.svg \
    modules/Material/icons/action/report_problem.svg \
    modules/Material/icons/action/restore.svg \
    modules/Material/icons/action/room.svg \
    modules/Material/icons/action/rounded_corner.svg \
    modules/Material/icons/action/rowing.svg \
    modules/Material/icons/action/schedule.svg \
    modules/Material/icons/action/search.svg \
    modules/Material/icons/action/settings.svg \
    modules/Material/icons/action/settings_applications.svg \
    modules/Material/icons/action/settings_backup_restore.svg \
    modules/Material/icons/action/settings_bluetooth.svg \
    modules/Material/icons/action/settings_brightness.svg \
    modules/Material/icons/action/settings_cell.svg \
    modules/Material/icons/action/settings_ethernet.svg \
    modules/Material/icons/action/settings_input_antenna.svg \
    modules/Material/icons/action/settings_input_component.svg \
    modules/Material/icons/action/settings_input_composite.svg \
    modules/Material/icons/action/settings_input_hdmi.svg \
    modules/Material/icons/action/settings_input_svideo.svg \
    modules/Material/icons/action/settings_overscan.svg \
    modules/Material/icons/action/settings_phone.svg \
    modules/Material/icons/action/settings_power.svg \
    modules/Material/icons/action/settings_remote.svg \
    modules/Material/icons/action/settings_voice.svg \
    modules/Material/icons/action/shop.svg \
    modules/Material/icons/action/shop_two.svg \
    modules/Material/icons/action/shopping_basket.svg \
    modules/Material/icons/action/shopping_cart.svg \
    modules/Material/icons/action/speaker_notes.svg \
    modules/Material/icons/action/spellcheck.svg \
    modules/Material/icons/action/stars.svg \
    modules/Material/icons/action/store.svg \
    modules/Material/icons/action/subject.svg \
    modules/Material/icons/action/supervisor_account.svg \
    modules/Material/icons/action/swap_horiz.svg \
    modules/Material/icons/action/swap_vert.svg \
    modules/Material/icons/action/swap_vertical_circle.svg \
    modules/Material/icons/action/system_update_alt.svg \
    modules/Material/icons/action/tab.svg \
    modules/Material/icons/action/tab_unselected.svg \
    modules/Material/icons/action/theaters.svg \
    modules/Material/icons/action/thumb_down.svg \
    modules/Material/icons/action/thumb_up.svg \
    modules/Material/icons/action/thumbs_up_down.svg \
    modules/Material/icons/action/timeline.svg \
    modules/Material/icons/action/toc.svg \
    modules/Material/icons/action/today.svg \
    modules/Material/icons/action/toll.svg \
    modules/Material/icons/action/touch_app.svg \
    modules/Material/icons/action/track_changes.svg \
    modules/Material/icons/action/translate.svg \
    modules/Material/icons/action/trending_down.svg \
    modules/Material/icons/action/trending_flat.svg \
    modules/Material/icons/action/trending_up.svg \
    modules/Material/icons/action/turned_in.svg \
    modules/Material/icons/action/turned_in_not.svg \
    modules/Material/icons/action/update.svg \
    modules/Material/icons/action/verified_user.svg \
    modules/Material/icons/action/view_agenda.svg \
    modules/Material/icons/action/view_array.svg \
    modules/Material/icons/action/view_carousel.svg \
    modules/Material/icons/action/view_column.svg \
    modules/Material/icons/action/view_day.svg \
    modules/Material/icons/action/view_headline.svg \
    modules/Material/icons/action/view_list.svg \
    modules/Material/icons/action/view_module.svg \
    modules/Material/icons/action/view_quilt.svg \
    modules/Material/icons/action/view_stream.svg \
    modules/Material/icons/action/view_week.svg \
    modules/Material/icons/action/visibility.svg \
    modules/Material/icons/action/visibility_off.svg \
    modules/Material/icons/action/watch_later.svg \
    modules/Material/icons/action/work.svg \
    modules/Material/icons/action/youtube_searched_for.svg \
    modules/Material/icons/action/zoom_in.svg \
    modules/Material/icons/action/zoom_out.svg \
    modules/Material/icons/alert/add_alert.svg \
    modules/Material/icons/alert/error.svg \
    modules/Material/icons/alert/error_outline.svg \
    modules/Material/icons/alert/warning.svg \
    modules/Material/icons/av/add_to_queue.svg \
    modules/Material/icons/av/airplay.svg \
    modules/Material/icons/av/album.svg \
    modules/Material/icons/av/art_track.svg \
    modules/Material/icons/av/av_timer.svg \
    modules/Material/icons/av/closed_caption.svg \
    modules/Material/icons/av/equalizer.svg \
    modules/Material/icons/av/explicit.svg \
    modules/Material/icons/av/fast_forward.svg \
    modules/Material/icons/av/fast_rewind.svg \
    modules/Material/icons/av/fiber_dvr.svg \
    modules/Material/icons/av/fiber_manual_record.svg \
    modules/Material/icons/av/fiber_new.svg \
    modules/Material/icons/av/fiber_pin.svg \
    modules/Material/icons/av/fiber_smart_record.svg \
    modules/Material/icons/av/forward_10.svg \
    modules/Material/icons/av/forward_30.svg \
    modules/Material/icons/av/forward_5.svg \
    modules/Material/icons/av/games.svg \
    modules/Material/icons/av/hd.svg \
    modules/Material/icons/av/hearing.svg \
    modules/Material/icons/av/high_quality.svg \
    modules/Material/icons/av/library_add.svg \
    modules/Material/icons/av/library_books.svg \
    modules/Material/icons/av/library_music.svg \
    modules/Material/icons/av/loop.svg \
    modules/Material/icons/av/mic.svg \
    modules/Material/icons/av/mic_none.svg \
    modules/Material/icons/av/mic_off.svg \
    modules/Material/icons/av/movie.svg \
    modules/Material/icons/av/music_video.svg \
    modules/Material/icons/av/new_releases.svg \
    modules/Material/icons/av/not_interested.svg \
    modules/Material/icons/av/pause.svg \
    modules/Material/icons/av/pause_circle_filled.svg \
    modules/Material/icons/av/pause_circle_outline.svg \
    modules/Material/icons/av/play_arrow.svg \
    modules/Material/icons/av/play_circle_filled.svg \
    modules/Material/icons/av/play_circle_outline.svg \
    modules/Material/icons/av/playlist_add.svg \
    modules/Material/icons/av/playlist_add_check.svg \
    modules/Material/icons/av/playlist_play.svg \
    modules/Material/icons/av/queue.svg \
    modules/Material/icons/av/queue_music.svg \
    modules/Material/icons/av/queue_play_next.svg \
    modules/Material/icons/av/radio.svg \
    modules/Material/icons/av/recent_actors.svg \
    modules/Material/icons/av/remove_from_queue.svg \
    modules/Material/icons/av/repeat.svg \
    modules/Material/icons/av/repeat_one.svg \
    modules/Material/icons/av/replay.svg \
    modules/Material/icons/av/replay_10.svg \
    modules/Material/icons/av/replay_30.svg \
    modules/Material/icons/av/replay_5.svg \
    modules/Material/icons/av/shuffle.svg \
    modules/Material/icons/av/skip_next.svg \
    modules/Material/icons/av/skip_previous.svg \
    modules/Material/icons/av/slow_motion_video.svg \
    modules/Material/icons/av/snooze.svg \
    modules/Material/icons/av/sort_by_alpha.svg \
    modules/Material/icons/av/stop.svg \
    modules/Material/icons/av/subscriptions.svg \
    modules/Material/icons/av/subtitles.svg \
    modules/Material/icons/av/surround_sound.svg \
    modules/Material/icons/av/video_library.svg \
    modules/Material/icons/av/videocam.svg \
    modules/Material/icons/av/videocam_off.svg \
    modules/Material/icons/av/volume_down.svg \
    modules/Material/icons/av/volume_mute.svg \
    modules/Material/icons/av/volume_off.svg \
    modules/Material/icons/av/volume_up.svg \
    modules/Material/icons/av/web.svg \
    modules/Material/icons/av/web_asset.svg \
    modules/Material/icons/communication/business.svg \
    modules/Material/icons/communication/call.svg \
    modules/Material/icons/communication/call_end.svg \
    modules/Material/icons/communication/call_made.svg \
    modules/Material/icons/communication/call_merge.svg \
    modules/Material/icons/communication/call_missed.svg \
    modules/Material/icons/communication/call_missed_outgoing.svg \
    modules/Material/icons/communication/call_received.svg \
    modules/Material/icons/communication/call_split.svg \
    modules/Material/icons/communication/chat.svg \
    modules/Material/icons/communication/chat_bubble.svg \
    modules/Material/icons/communication/chat_bubble_outline.svg \
    modules/Material/icons/communication/clear_all.svg \
    modules/Material/icons/communication/comment.svg \
    modules/Material/icons/communication/contact_mail.svg \
    modules/Material/icons/communication/contact_mail_24px.svg \
    modules/Material/icons/communication/contact_mail_48px.svg \
    modules/Material/icons/communication/contact_phone.svg \
    modules/Material/icons/communication/contacts.svg \
    modules/Material/icons/communication/dialer_sip.svg \
    modules/Material/icons/communication/dialpad.svg \
    modules/Material/icons/communication/email.svg \
    modules/Material/icons/communication/forum.svg \
    modules/Material/icons/communication/import_contacts.svg \
    modules/Material/icons/communication/import_export.svg \
    modules/Material/icons/communication/invert_colors_off.svg \
    modules/Material/icons/communication/live_help.svg \
    modules/Material/icons/communication/location_off.svg \
    modules/Material/icons/communication/location_on.svg \
    modules/Material/icons/communication/mail_outline.svg \
    modules/Material/icons/communication/message.svg \
    modules/Material/icons/communication/no_sim.svg \
    modules/Material/icons/communication/phone.svg \
    modules/Material/icons/communication/phonelink_erase.svg \
    modules/Material/icons/communication/phonelink_lock.svg \
    modules/Material/icons/communication/phonelink_ring.svg \
    modules/Material/icons/communication/phonelink_setup.svg \
    modules/Material/icons/communication/portable_wifi_off.svg \
    modules/Material/icons/communication/present_to_all.svg \
    modules/Material/icons/communication/ring_volume.svg \
    modules/Material/icons/communication/screen_share.svg \
    modules/Material/icons/communication/speaker_phone.svg \
    modules/Material/icons/communication/stay_current_landscape.svg \
    modules/Material/icons/communication/stay_current_portrait.svg \
    modules/Material/icons/communication/stay_primary_landscape.svg \
    modules/Material/icons/communication/stay_primary_portrait.svg \
    modules/Material/icons/communication/stop_screen_share.svg \
    modules/Material/icons/communication/swap_calls.svg \
    modules/Material/icons/communication/textsms.svg \
    modules/Material/icons/communication/voicemail.svg \
    modules/Material/icons/communication/vpn_key.svg \
    modules/Material/icons/content/add.svg \
    modules/Material/icons/content/add_box.svg \
    modules/Material/icons/content/add_circle.svg \
    modules/Material/icons/content/add_circle_outline.svg \
    modules/Material/icons/content/archive.svg \
    modules/Material/icons/content/backspace.svg \
    modules/Material/icons/content/block.svg \
    modules/Material/icons/content/clear.svg \
    modules/Material/icons/content/content_copy.svg \
    modules/Material/icons/content/content_cut.svg \
    modules/Material/icons/content/content_paste.svg \
    modules/Material/icons/content/create.svg \
    modules/Material/icons/content/drafts.svg \
    modules/Material/icons/content/filter_list.svg \
    modules/Material/icons/content/flag.svg \
    modules/Material/icons/content/font_download.svg \
    modules/Material/icons/content/forward.svg \
    modules/Material/icons/content/gesture.svg \
    modules/Material/icons/content/inbox.svg \
    modules/Material/icons/content/link.svg \
    modules/Material/icons/content/mail.svg \
    modules/Material/icons/content/markunread.svg \
    modules/Material/icons/content/move_to_inbox.svg \
    modules/Material/icons/content/next_week.svg \
    modules/Material/icons/content/redo.svg \
    modules/Material/icons/content/remove.svg \
    modules/Material/icons/content/remove_circle.svg \
    modules/Material/icons/content/remove_circle_outline.svg \
    modules/Material/icons/content/reply.svg \
    modules/Material/icons/content/reply_all.svg \
    modules/Material/icons/content/report.svg \
    modules/Material/icons/content/save.svg \
    modules/Material/icons/content/select_all.svg \
    modules/Material/icons/content/send.svg \
    modules/Material/icons/content/sort.svg \
    modules/Material/icons/content/text_format.svg \
    modules/Material/icons/content/unarchive.svg \
    modules/Material/icons/content/undo.svg \
    modules/Material/icons/content/weekend.svg \
    modules/Material/icons/device/access_alarm.svg \
    modules/Material/icons/device/access_alarms.svg \
    modules/Material/icons/device/access_time.svg \
    modules/Material/icons/device/add_alarm.svg \
    modules/Material/icons/device/airplanemode_active.svg \
    modules/Material/icons/device/airplanemode_inactive.svg \
    modules/Material/icons/device/battery_20.svg \
    modules/Material/icons/device/battery_30.svg \
    modules/Material/icons/device/battery_50.svg \
    modules/Material/icons/device/battery_60.svg \
    modules/Material/icons/device/battery_80.svg \
    modules/Material/icons/device/battery_90.svg \
    modules/Material/icons/device/battery_alert.svg \
    modules/Material/icons/device/battery_charging_20.svg \
    modules/Material/icons/device/battery_charging_30.svg \
    modules/Material/icons/device/battery_charging_50.svg \
    modules/Material/icons/device/battery_charging_60.svg \
    modules/Material/icons/device/battery_charging_80.svg \
    modules/Material/icons/device/battery_charging_90.svg \
    modules/Material/icons/device/battery_charging_full.svg \
    modules/Material/icons/device/battery_full.svg \
    modules/Material/icons/device/battery_std.svg \
    modules/Material/icons/device/battery_unknown.svg \
    modules/Material/icons/device/bluetooth.svg \
    modules/Material/icons/device/bluetooth_connected.svg \
    modules/Material/icons/device/bluetooth_disabled.svg \
    modules/Material/icons/device/bluetooth_searching.svg \
    modules/Material/icons/device/brightness_auto.svg \
    modules/Material/icons/device/brightness_high.svg \
    modules/Material/icons/device/brightness_low.svg \
    modules/Material/icons/device/brightness_medium.svg \
    modules/Material/icons/device/data_usage.svg \
    modules/Material/icons/device/developer_mode.svg \
    modules/Material/icons/device/devices.svg \
    modules/Material/icons/device/dvr.svg \
    modules/Material/icons/device/gps_fixed.svg \
    modules/Material/icons/device/gps_not_fixed.svg \
    modules/Material/icons/device/gps_off.svg \
    modules/Material/icons/device/graphic_eq.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_1_bar_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_2_bar_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_3_bar_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_4_bar_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_connected_no_internet_1_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_connected_no_internet_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_connected_no_internet_2_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_connected_no_internet_3_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_connected_no_internet_4_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_not_connected_26x24px.svg \
    modules/Material/icons/device/ic_signal_wifi_statusbar_null_26x24px.svg \
    modules/Material/icons/device/location_disabled.svg \
    modules/Material/icons/device/location_searching.svg \
    modules/Material/icons/device/network_cell.svg \
    modules/Material/icons/device/network_wifi.svg \
    modules/Material/icons/device/nfc.svg \
    modules/Material/icons/device/screen_lock_landscape.svg \
    modules/Material/icons/device/screen_lock_portrait.svg \
    modules/Material/icons/device/screen_lock_rotation.svg \
    modules/Material/icons/device/screen_rotation.svg \
    modules/Material/icons/device/sd_storage.svg \
    modules/Material/icons/device/settings_system_daydream.svg \
    modules/Material/icons/device/signal_cellular_0_bar.svg \
    modules/Material/icons/device/signal_cellular_1_bar.svg \
    modules/Material/icons/device/signal_cellular_2_bar.svg \
    modules/Material/icons/device/signal_cellular_3_bar.svg \
    modules/Material/icons/device/signal_cellular_4_bar.svg \
    modules/Material/icons/device/signal_cellular_connected_no_internet_0_bar.svg \
    modules/Material/icons/device/signal_cellular_connected_no_internet_1_bar.svg \
    modules/Material/icons/device/signal_cellular_connected_no_internet_2_bar.svg \
    modules/Material/icons/device/signal_cellular_connected_no_internet_3_bar.svg \
    modules/Material/icons/device/signal_cellular_connected_no_internet_4_bar.svg \
    modules/Material/icons/device/signal_cellular_no_sim.svg \
    modules/Material/icons/device/signal_cellular_null.svg \
    modules/Material/icons/device/signal_cellular_off.svg \
    modules/Material/icons/device/signal_wifi_0_bar.svg \
    modules/Material/icons/device/signal_wifi_1_bar.svg \
    modules/Material/icons/device/signal_wifi_1_bar_lock.svg \
    modules/Material/icons/device/signal_wifi_2_bar.svg \
    modules/Material/icons/device/signal_wifi_2_bar_lock.svg \
    modules/Material/icons/device/signal_wifi_3_bar.svg \
    modules/Material/icons/device/signal_wifi_3_bar_lock.svg \
    modules/Material/icons/device/signal_wifi_4_bar.svg \
    modules/Material/icons/device/signal_wifi_4_bar_lock.svg \
    modules/Material/icons/device/signal_wifi_off.svg \
    modules/Material/icons/device/storage.svg \
    modules/Material/icons/device/usb.svg \
    modules/Material/icons/device/wallpaper.svg \
    modules/Material/icons/device/widgets.svg \
    modules/Material/icons/device/wifi_lock.svg \
    modules/Material/icons/device/wifi_tethering.svg \
    modules/Material/icons/editor/attach_file.svg \
    modules/Material/icons/editor/attach_money.svg \
    modules/Material/icons/editor/border_all.svg \
    modules/Material/icons/editor/border_bottom.svg \
    modules/Material/icons/editor/border_clear.svg \
    modules/Material/icons/editor/border_color.svg \
    modules/Material/icons/editor/border_horizontal.svg \
    modules/Material/icons/editor/border_inner.svg \
    modules/Material/icons/editor/border_left.svg \
    modules/Material/icons/editor/border_outer.svg \
    modules/Material/icons/editor/border_right.svg \
    modules/Material/icons/editor/border_style.svg \
    modules/Material/icons/editor/border_top.svg \
    modules/Material/icons/editor/border_vertical.svg \
    modules/Material/icons/editor/drag_handle.svg \
    modules/Material/icons/editor/format_align_center.svg \
    modules/Material/icons/editor/format_align_justify.svg \
    modules/Material/icons/editor/format_align_left.svg \
    modules/Material/icons/editor/format_align_right.svg \
    modules/Material/icons/editor/format_bold.svg \
    modules/Material/icons/editor/format_clear.svg \
    modules/Material/icons/editor/format_color_fill.svg \
    modules/Material/icons/editor/format_color_reset.svg \
    modules/Material/icons/editor/format_color_text.svg \
    modules/Material/icons/editor/format_indent_decrease.svg \
    modules/Material/icons/editor/format_indent_increase.svg \
    modules/Material/icons/editor/format_italic.svg \
    modules/Material/icons/editor/format_line_spacing.svg \
    modules/Material/icons/editor/format_list_bulleted.svg \
    modules/Material/icons/editor/format_list_numbered.svg \
    modules/Material/icons/editor/format_paint.svg \
    modules/Material/icons/editor/format_quote.svg \
    modules/Material/icons/editor/format_shapes.svg \
    modules/Material/icons/editor/format_size.svg \
    modules/Material/icons/editor/format_strikethrough.svg \
    modules/Material/icons/editor/format_textdirection_l_to_r.svg \
    modules/Material/icons/editor/format_textdirection_r_to_l.svg \
    modules/Material/icons/editor/format_underlined.svg \
    modules/Material/icons/editor/functions.svg \
    modules/Material/icons/editor/highlight.svg \
    modules/Material/icons/editor/insert_chart.svg \
    modules/Material/icons/editor/insert_comment.svg \
    modules/Material/icons/editor/insert_drive_file.svg \
    modules/Material/icons/editor/insert_emoticon.svg \
    modules/Material/icons/editor/insert_invitation.svg \
    modules/Material/icons/editor/insert_link.svg \
    modules/Material/icons/editor/insert_photo.svg \
    modules/Material/icons/editor/linear_scale.svg \
    modules/Material/icons/editor/merge_type.svg \
    modules/Material/icons/editor/mode_comment.svg \
    modules/Material/icons/editor/mode_edit.svg \
    modules/Material/icons/editor/money_off.svg \
    modules/Material/icons/editor/publish.svg \
    modules/Material/icons/editor/short_text.svg \
    modules/Material/icons/editor/space_bar.svg \
    modules/Material/icons/editor/strikethrough_s.svg \
    modules/Material/icons/editor/text_fields.svg \
    modules/Material/icons/editor/vertical_align_bottom.svg \
    modules/Material/icons/editor/vertical_align_center.svg \
    modules/Material/icons/editor/vertical_align_top.svg \
    modules/Material/icons/editor/wrap_text.svg \
    modules/Material/icons/file/attachment.svg \
    modules/Material/icons/file/cloud.svg \
    modules/Material/icons/file/cloud_circle.svg \
    modules/Material/icons/file/cloud_done.svg \
    modules/Material/icons/file/cloud_download.svg \
    modules/Material/icons/file/cloud_off.svg \
    modules/Material/icons/file/cloud_queue.svg \
    modules/Material/icons/file/cloud_upload.svg \
    modules/Material/icons/file/create_new_folder.svg \
    modules/Material/icons/file/file_download.svg \
    modules/Material/icons/file/file_upload.svg \
    modules/Material/icons/file/folder.svg \
    modules/Material/icons/file/folder_open.svg \
    modules/Material/icons/file/folder_shared.svg \
    modules/Material/icons/hardware/cast.svg \
    modules/Material/icons/hardware/cast_connected.svg \
    modules/Material/icons/hardware/computer.svg \
    modules/Material/icons/hardware/desktop_mac.svg \
    modules/Material/icons/hardware/desktop_windows.svg \
    modules/Material/icons/hardware/developer_board.svg \
    modules/Material/icons/hardware/device_hub.svg \
    modules/Material/icons/hardware/devices_other.svg \
    modules/Material/icons/hardware/dock.svg \
    modules/Material/icons/hardware/gamepad.svg \
    modules/Material/icons/hardware/headset.svg \
    modules/Material/icons/hardware/headset_mic.svg \
    modules/Material/icons/hardware/keyboard.svg \
    modules/Material/icons/hardware/keyboard_arrow_down.svg \
    modules/Material/icons/hardware/keyboard_arrow_left.svg \
    modules/Material/icons/hardware/keyboard_arrow_right.svg \
    modules/Material/icons/hardware/keyboard_arrow_up.svg \
    modules/Material/icons/hardware/keyboard_backspace.svg \
    modules/Material/icons/hardware/keyboard_capslock.svg \
    modules/Material/icons/hardware/keyboard_hide.svg \
    modules/Material/icons/hardware/keyboard_return.svg \
    modules/Material/icons/hardware/keyboard_tab.svg \
    modules/Material/icons/hardware/keyboard_voice.svg \
    modules/Material/icons/hardware/laptop.svg \
    modules/Material/icons/hardware/laptop_chromebook.svg \
    modules/Material/icons/hardware/laptop_mac.svg \
    modules/Material/icons/hardware/laptop_windows.svg \
    modules/Material/icons/hardware/memory.svg \
    modules/Material/icons/hardware/mouse.svg \
    modules/Material/icons/hardware/phone_android.svg \
    modules/Material/icons/hardware/phone_iphone.svg \
    modules/Material/icons/hardware/phonelink.svg \
    modules/Material/icons/hardware/phonelink_off.svg \
    modules/Material/icons/hardware/power_input.svg \
    modules/Material/icons/hardware/router.svg \
    modules/Material/icons/hardware/scanner.svg \
    modules/Material/icons/hardware/security.svg \
    modules/Material/icons/hardware/sim_card.svg \
    modules/Material/icons/hardware/smartphone.svg \
    modules/Material/icons/hardware/speaker.svg \
    modules/Material/icons/hardware/speaker_group.svg \
    modules/Material/icons/hardware/tablet.svg \
    modules/Material/icons/hardware/tablet_android.svg \
    modules/Material/icons/hardware/tablet_mac.svg \
    modules/Material/icons/hardware/toys.svg \
    modules/Material/icons/hardware/tv.svg \
    modules/Material/icons/hardware/videogame_asset.svg \
    modules/Material/icons/hardware/watch.svg \
    modules/Material/icons/image/add_a_photo.svg \
    modules/Material/icons/image/add_to_photos.svg \
    modules/Material/icons/image/adjust.svg \
    modules/Material/icons/image/assistant.svg \
    modules/Material/icons/image/assistant_photo.svg \
    modules/Material/icons/image/audiotrack.svg \
    modules/Material/icons/image/blur_circular.svg \
    modules/Material/icons/image/blur_linear.svg \
    modules/Material/icons/image/blur_off.svg \
    modules/Material/icons/image/blur_on.svg \
    modules/Material/icons/image/brightness_1.svg \
    modules/Material/icons/image/brightness_2.svg \
    modules/Material/icons/image/brightness_3.svg \
    modules/Material/icons/image/brightness_4.svg \
    modules/Material/icons/image/brightness_5.svg \
    modules/Material/icons/image/brightness_6.svg \
    modules/Material/icons/image/brightness_7.svg \
    modules/Material/icons/image/broken_image.svg \
    modules/Material/icons/image/brush.svg \
    modules/Material/icons/image/camera.svg \
    modules/Material/icons/image/camera_alt.svg \
    modules/Material/icons/image/camera_front.svg \
    modules/Material/icons/image/camera_rear.svg \
    modules/Material/icons/image/camera_roll.svg \
    modules/Material/icons/image/center_focus_strong.svg \
    modules/Material/icons/image/center_focus_weak.svg \
    modules/Material/icons/image/collections.svg \
    modules/Material/icons/image/collections_bookmark.svg \
    modules/Material/icons/image/color_lens.svg \
    modules/Material/icons/image/colorize.svg \
    modules/Material/icons/image/compare.svg \
    modules/Material/icons/image/control_point.svg \
    modules/Material/icons/image/control_point_duplicate.svg \
    modules/Material/icons/image/crop.svg \
    modules/Material/icons/image/crop_16_9.svg \
    modules/Material/icons/image/crop_3_2.svg \
    modules/Material/icons/image/crop_5_4.svg \
    modules/Material/icons/image/crop_7_5.svg \
    modules/Material/icons/image/crop_din.svg \
    modules/Material/icons/image/crop_free.svg \
    modules/Material/icons/image/crop_landscape.svg \
    modules/Material/icons/image/crop_original.svg \
    modules/Material/icons/image/crop_portrait.svg \
    modules/Material/icons/image/crop_rotate.svg \
    modules/Material/icons/image/crop_square.svg \
    modules/Material/icons/image/dehaze.svg \
    modules/Material/icons/image/details.svg \
    modules/Material/icons/image/edit.svg \
    modules/Material/icons/image/exposure.svg \
    modules/Material/icons/image/exposure_neg_1.svg \
    modules/Material/icons/image/exposure_neg_2.svg \
    modules/Material/icons/image/exposure_plus_1.svg \
    modules/Material/icons/image/exposure_plus_2.svg \
    modules/Material/icons/image/exposure_zero.svg \
    modules/Material/icons/image/filter.svg \
    modules/Material/icons/image/filter_1.svg \
    modules/Material/icons/image/filter_2.svg \
    modules/Material/icons/image/filter_3.svg \
    modules/Material/icons/image/filter_4.svg \
    modules/Material/icons/image/filter_5.svg \
    modules/Material/icons/image/filter_6.svg \
    modules/Material/icons/image/filter_7.svg \
    modules/Material/icons/image/filter_8.svg \
    modules/Material/icons/image/filter_9.svg \
    modules/Material/icons/image/filter_9_plus.svg \
    modules/Material/icons/image/filter_b_and_w.svg \
    modules/Material/icons/image/filter_center_focus.svg \
    modules/Material/icons/image/filter_drama.svg \
    modules/Material/icons/image/filter_frames.svg \
    modules/Material/icons/image/filter_hdr.svg \
    modules/Material/icons/image/filter_none.svg \
    modules/Material/icons/image/filter_tilt_shift.svg \
    modules/Material/icons/image/filter_vintage.svg \
    modules/Material/icons/image/flare.svg \
    modules/Material/icons/image/flash_auto.svg \
    modules/Material/icons/image/flash_off.svg \
    modules/Material/icons/image/flash_on.svg \
    modules/Material/icons/image/flip.svg \
    modules/Material/icons/image/gradient.svg \
    modules/Material/icons/image/grain.svg \
    modules/Material/icons/image/grid_off.svg \
    modules/Material/icons/image/grid_on.svg \
    modules/Material/icons/image/hdr_off.svg \
    modules/Material/icons/image/hdr_on.svg \
    modules/Material/icons/image/hdr_strong.svg \
    modules/Material/icons/image/hdr_weak.svg \
    modules/Material/icons/image/healing.svg \
    modules/Material/icons/image/image.svg \
    modules/Material/icons/image/image_aspect_ratio.svg \
    modules/Material/icons/image/iso.svg \
    modules/Material/icons/image/landscape.svg \
    modules/Material/icons/image/leak_add.svg \
    modules/Material/icons/image/leak_remove.svg \
    modules/Material/icons/image/lens.svg \
    modules/Material/icons/image/linked_camera.svg \
    modules/Material/icons/image/looks.svg \
    modules/Material/icons/image/looks_3.svg \
    modules/Material/icons/image/looks_4.svg \
    modules/Material/icons/image/looks_5.svg \
    modules/Material/icons/image/looks_6.svg \
    modules/Material/icons/image/looks_one.svg \
    modules/Material/icons/image/looks_two.svg \
    modules/Material/icons/image/loupe.svg \
    modules/Material/icons/image/monochrome_photos.svg \
    modules/Material/icons/image/movie_creation.svg \
    modules/Material/icons/image/movie_filter.svg \
    modules/Material/icons/image/music_note.svg \
    modules/Material/icons/image/nature.svg \
    modules/Material/icons/image/nature_people.svg \
    modules/Material/icons/image/navigate_before.svg \
    modules/Material/icons/image/navigate_next.svg \
    modules/Material/icons/image/palette.svg \
    modules/Material/icons/image/panorama.svg \
    modules/Material/icons/image/panorama_fish_eye.svg \
    modules/Material/icons/image/panorama_horizontal.svg \
    modules/Material/icons/image/panorama_vertical.svg \
    modules/Material/icons/image/panorama_wide_angle.svg \
    modules/Material/icons/image/photo.svg \
    modules/Material/icons/image/photo_album.svg \
    modules/Material/icons/image/photo_camera.svg \
    modules/Material/icons/image/photo_filter.svg \
    modules/Material/icons/image/photo_library.svg \
    modules/Material/icons/image/photo_size_select_actual.svg \
    modules/Material/icons/image/photo_size_select_large.svg \
    modules/Material/icons/image/photo_size_select_small.svg \
    modules/Material/icons/image/picture_as_pdf.svg \
    modules/Material/icons/image/portrait.svg \
    modules/Material/icons/image/remove_red_eye.svg \
    modules/Material/icons/image/rotate_90_degrees_ccw.svg \
    modules/Material/icons/image/rotate_left.svg \
    modules/Material/icons/image/rotate_right.svg \
    modules/Material/icons/image/slideshow.svg \
    modules/Material/icons/image/straighten.svg \
    modules/Material/icons/image/style.svg \
    modules/Material/icons/image/switch_camera.svg \
    modules/Material/icons/image/switch_video.svg \
    modules/Material/icons/image/tag_faces.svg \
    modules/Material/icons/image/texture.svg \
    modules/Material/icons/image/timelapse.svg \
    modules/Material/icons/image/timer.svg \
    modules/Material/icons/image/timer_10.svg \
    modules/Material/icons/image/timer_3.svg \
    modules/Material/icons/image/timer_off.svg \
    modules/Material/icons/image/tonality.svg \
    modules/Material/icons/image/transform.svg \
    modules/Material/icons/image/tune.svg \
    modules/Material/icons/image/view_comfy.svg \
    modules/Material/icons/image/view_compact.svg \
    modules/Material/icons/image/vignette.svg \
    modules/Material/icons/image/wb_auto.svg \
    modules/Material/icons/image/wb_cloudy.svg \
    modules/Material/icons/image/wb_incandescent.svg \
    modules/Material/icons/image/wb_iridescent.svg \
    modules/Material/icons/image/wb_sunny.svg \
    modules/Material/icons/maps/add_location.svg \
    modules/Material/icons/maps/beenhere.svg \
    modules/Material/icons/maps/directions.svg \
    modules/Material/icons/maps/directions_bike.svg \
    modules/Material/icons/maps/directions_boat.svg \
    modules/Material/icons/maps/directions_bus.svg \
    modules/Material/icons/maps/directions_car.svg \
    modules/Material/icons/maps/directions_railway.svg \
    modules/Material/icons/maps/directions_run.svg \
    modules/Material/icons/maps/directions_subway.svg \
    modules/Material/icons/maps/directions_transit.svg \
    modules/Material/icons/maps/directions_walk.svg \
    modules/Material/icons/maps/edit_location.svg \
    modules/Material/icons/maps/flight.svg \
    modules/Material/icons/maps/hotel.svg \
    modules/Material/icons/maps/layers.svg \
    modules/Material/icons/maps/layers_clear.svg \
    modules/Material/icons/maps/local_activity.svg \
    modules/Material/icons/maps/local_airport.svg \
    modules/Material/icons/maps/local_atm.svg \
    modules/Material/icons/maps/local_bar.svg \
    modules/Material/icons/maps/local_cafe.svg \
    modules/Material/icons/maps/local_car_wash.svg \
    modules/Material/icons/maps/local_convenience_store.svg \
    modules/Material/icons/maps/local_dining.svg \
    modules/Material/icons/maps/local_drink.svg \
    modules/Material/icons/maps/local_florist.svg \
    modules/Material/icons/maps/local_gas_station.svg \
    modules/Material/icons/maps/local_grocery_store.svg \
    modules/Material/icons/maps/local_hospital.svg \
    modules/Material/icons/maps/local_hotel.svg \
    modules/Material/icons/maps/local_laundry_service.svg \
    modules/Material/icons/maps/local_library.svg \
    modules/Material/icons/maps/local_mall.svg \
    modules/Material/icons/maps/local_movies.svg \
    modules/Material/icons/maps/local_offer.svg \
    modules/Material/icons/maps/local_parking.svg \
    modules/Material/icons/maps/local_pharmacy.svg \
    modules/Material/icons/maps/local_phone.svg \
    modules/Material/icons/maps/local_pizza.svg \
    modules/Material/icons/maps/local_play.svg \
    modules/Material/icons/maps/local_post_office.svg \
    modules/Material/icons/maps/local_printshop.svg \
    modules/Material/icons/maps/local_see.svg \
    modules/Material/icons/maps/local_shipping.svg \
    modules/Material/icons/maps/local_taxi.svg \
    modules/Material/icons/maps/map.svg \
    modules/Material/icons/maps/my_location.svg \
    modules/Material/icons/maps/navigation.svg \
    modules/Material/icons/maps/near_me.svg \
    modules/Material/icons/maps/person_pin.svg \
    modules/Material/icons/maps/person_pin_circle.svg \
    modules/Material/icons/maps/pin_drop.svg \
    modules/Material/icons/maps/place.svg \
    modules/Material/icons/maps/rate_review.svg \
    modules/Material/icons/maps/restaurant_menu.svg \
    modules/Material/icons/maps/satellite.svg \
    modules/Material/icons/maps/store_mall_directory.svg \
    modules/Material/icons/maps/terrain.svg \
    modules/Material/icons/maps/traffic.svg \
    modules/Material/icons/maps/zoom_out_map.svg \
    modules/Material/icons/navigation/apps.svg \
    modules/Material/icons/navigation/arrow_back.svg \
    modules/Material/icons/navigation/arrow_downward.svg \
    modules/Material/icons/navigation/arrow_drop_down.svg \
    modules/Material/icons/navigation/arrow_drop_down_circle.svg \
    modules/Material/icons/navigation/arrow_drop_up.svg \
    modules/Material/icons/navigation/arrow_forward.svg \
    modules/Material/icons/navigation/arrow_upward.svg \
    modules/Material/icons/navigation/cancel.svg \
    modules/Material/icons/navigation/check.svg \
    modules/Material/icons/navigation/chevron_left.svg \
    modules/Material/icons/navigation/chevron_right.svg \
    modules/Material/icons/navigation/close.svg \
    modules/Material/icons/navigation/expand_less.svg \
    modules/Material/icons/navigation/expand_more.svg \
    modules/Material/icons/navigation/fullscreen.svg \
    modules/Material/icons/navigation/fullscreen_exit.svg \
    modules/Material/icons/navigation/menu.svg \
    modules/Material/icons/navigation/more_horiz.svg \
    modules/Material/icons/navigation/more_vert.svg \
    modules/Material/icons/navigation/refresh.svg \
    modules/Material/icons/navigation/subdirectory_arrow_left.svg \
    modules/Material/icons/navigation/subdirectory_arrow_right.svg \
    modules/Material/icons/navigation/unfold_less.svg \
    modules/Material/icons/navigation/unfold_more.svg \
    modules/Material/icons/notification/adb.svg \
    modules/Material/icons/notification/airline_seat_flat.svg \
    modules/Material/icons/notification/airline_seat_flat_angled.svg \
    modules/Material/icons/notification/airline_seat_individual_suite.svg \
    modules/Material/icons/notification/airline_seat_legroom_extra.svg \
    modules/Material/icons/notification/airline_seat_legroom_normal.svg \
    modules/Material/icons/notification/airline_seat_legroom_reduced.svg \
    modules/Material/icons/notification/airline_seat_recline_extra.svg \
    modules/Material/icons/notification/airline_seat_recline_normal.svg \
    modules/Material/icons/notification/bluetooth_audio.svg \
    modules/Material/icons/notification/confirmation_number.svg \
    modules/Material/icons/notification/disc_full.svg \
    modules/Material/icons/notification/do_not_disturb.svg \
    modules/Material/icons/notification/do_not_disturb_alt.svg \
    modules/Material/icons/notification/drive_eta.svg \
    modules/Material/icons/notification/enhanced_encryption.svg \
    modules/Material/icons/notification/event_available.svg \
    modules/Material/icons/notification/event_busy.svg \
    modules/Material/icons/notification/event_note.svg \
    modules/Material/icons/notification/folder_special.svg \
    modules/Material/icons/notification/live_tv.svg \
    modules/Material/icons/notification/mms.svg \
    modules/Material/icons/notification/more.svg \
    modules/Material/icons/notification/network_check.svg \
    modules/Material/icons/notification/network_locked.svg \
    modules/Material/icons/notification/no_encryption.svg \
    modules/Material/icons/notification/ondemand_video.svg \
    modules/Material/icons/notification/personal_video.svg \
    modules/Material/icons/notification/phone_bluetooth_speaker.svg \
    modules/Material/icons/notification/phone_forwarded.svg \
    modules/Material/icons/notification/phone_in_talk.svg \
    modules/Material/icons/notification/phone_locked.svg \
    modules/Material/icons/notification/phone_missed.svg \
    modules/Material/icons/notification/phone_paused.svg \
    modules/Material/icons/notification/power.svg \
    modules/Material/icons/notification/rv_hookup.svg \
    modules/Material/icons/notification/sd_card.svg \
    modules/Material/icons/notification/sim_card_alert.svg \
    modules/Material/icons/notification/sms.svg \
    modules/Material/icons/notification/sms_failed.svg \
    modules/Material/icons/notification/sync.svg \
    modules/Material/icons/notification/sync_disabled.svg \
    modules/Material/icons/notification/sync_problem.svg \
    modules/Material/icons/notification/system_update.svg \
    modules/Material/icons/notification/tap_and_play.svg \
    modules/Material/icons/notification/time_to_leave.svg \
    modules/Material/icons/notification/vibration.svg \
    modules/Material/icons/notification/voice_chat.svg \
    modules/Material/icons/notification/vpn_lock.svg \
    modules/Material/icons/notification/wc.svg \
    modules/Material/icons/notification/wifi.svg \
    modules/Material/icons/social/cake.svg \
    modules/Material/icons/social/domain.svg \
    modules/Material/icons/social/group.svg \
    modules/Material/icons/social/group_add.svg \
    modules/Material/icons/social/location_city.svg \
    modules/Material/icons/social/mood.svg \
    modules/Material/icons/social/mood_bad.svg \
    modules/Material/icons/social/notifications.svg \
    modules/Material/icons/social/notifications_active.svg \
    modules/Material/icons/social/notifications_none.svg \
    modules/Material/icons/social/notifications_off.svg \
    modules/Material/icons/social/notifications_paused.svg \
    modules/Material/icons/social/pages.svg \
    modules/Material/icons/social/party_mode.svg \
    modules/Material/icons/social/people.svg \
    modules/Material/icons/social/people_outline.svg \
    modules/Material/icons/social/person.svg \
    modules/Material/icons/social/person_add.svg \
    modules/Material/icons/social/person_outline.svg \
    modules/Material/icons/social/plus_one.svg \
    modules/Material/icons/social/poll.svg \
    modules/Material/icons/social/public.svg \
    modules/Material/icons/social/school.svg \
    modules/Material/icons/social/share.svg \
    modules/Material/icons/social/whatshot.svg \
    modules/Material/icons/toggle/check_box.svg \
    modules/Material/icons/toggle/check_box_outline_blank.svg \
    modules/Material/icons/toggle/indeterminate_check_box.svg \
    modules/Material/icons/toggle/radio_button_checked.svg \
    modules/Material/icons/toggle/radio_button_unchecked.svg \
    modules/Material/icons/toggle/star.svg \
    modules/Material/icons/toggle/star_border.svg \
    modules/Material/icons/toggle/star_half.svg \
    modules/Material/Extras/AutomaticGrid.qml \
    modules/Material/Extras/CircleImage.qml \
    modules/Material/Extras/CircleMask.qml \
    modules/Material/Extras/ColumnFlow.qml \
    modules/Material/Extras/Document.qml \
    modules/Material/Extras/Image.qml \
    modules/Material/Extras/Object.qml \
    modules/Material/ListItems/BaseListItem.qml \
    modules/Material/ListItems/Divider.qml \
    modules/Material/ListItems/SectionHeader.qml \
    modules/Material/ListItems/SimpleMenu.qml \
    modules/Material/ListItems/Standard.qml \
    modules/Material/ListItems/Subheader.qml \
    modules/Material/ListItems/Subtitled.qml \
    modules/Material/Action.qml \
    modules/Material/ActionBar.qml \
    modules/Material/ActionButton.qml \
    modules/Material/ApplicationWindow.qml \
    modules/Material/AppTheme.qml \
    modules/Material/AwesomeIcon.qml \
    modules/Material/BottomActionSheet.qml \
    modules/Material/BottomSheet.qml \
    modules/Material/Button.qml \
    modules/Material/Card.qml \
    modules/Material/CheckBox.qml \
    modules/Material/DatePicker.qml \
    modules/Material/Device.qml \
    modules/Material/Dialog.qml \
    modules/Material/Dropdown.qml \
    modules/Material/Icon.qml \
    modules/Material/IconButton.qml \
    modules/Material/Ink.qml \
    modules/Material/InputDialog.qml \
    modules/Material/Label.qml \
    modules/Material/MainView.qml \
    modules/Material/MaterialAnimation.qml \
    modules/Material/MenuField.qml \
    modules/Material/NavigationDrawer.qml \
    modules/Material/NavigationDrawerPage.qml \
    modules/Material/Object.qml \
    modules/Material/OverlayLayer.qml \
    modules/Material/OverlayView.qml \
    modules/Material/Page.qml \
    modules/Material/PageSidebar.qml \
    modules/Material/PageStack.qml \
    modules/Material/Palette.qml \
    modules/Material/PlatformExtensions.qml \
    modules/Material/Popover.qml \
    modules/Material/PopupBase.qml \
    modules/Material/ProgressBar.qml \
    modules/Material/ProgressCircle.qml \
    modules/Material/RadioButton.qml \
    modules/Material/Scrollbar.qml \
    modules/Material/Sidebar.qml \
    modules/Material/Slider.qml \
    modules/Material/Snackbar.qml \
    modules/Material/Switch.qml \
    modules/Material/Tab.qml \
    modules/Material/TabBar.qml \
    modules/Material/TabbedPage.qml \
    modules/Material/TextField.qml \
    modules/Material/Theme.qml \
    modules/Material/ThemePalette.qml \
    modules/Material/ThinDivider.qml \
    modules/Material/TimePicker.qml \
    modules/Material/TimePickerDialog.qml \
    modules/Material/Toolbar.qml \
    modules/Material/Tooltip.qml \
    modules/Material/Units.qml \
    modules/Material/View.qml \
    modules/Material/Wave.qml \
    modules/Material/Window.qml \
    modules/QtQuick/Controls/Styles/Material/ApplicationWindowStyle.qml \
    modules/QtQuick/Controls/Styles/Material/ButtonStyle.qml \
    modules/QtQuick/Controls/Styles/Material/CheckBoxStyle.qml \
    modules/QtQuick/Controls/Styles/Material/ProgressBarStyle.qml \
    modules/QtQuick/Controls/Styles/Material/RadioButtonStyle.qml \
    modules/QtQuick/Controls/Styles/Material/SliderStyle.qml \
    modules/QtQuick/Controls/Styles/Material/SwitchStyle.qml \
    modules/QtQuick/Controls/Styles/Material/TextFieldStyle.qml \
    modules/QtQuick/Controls/Styles/Material/ToolBarStyle.qml \
    modules/QtQuick/Controls/Styles/Material/ToolButtonStyle.qml
